input {
  beats {
    port => 5044
    ssl => false
  }

  syslog {
    port => 5000
    type => "syslog"
  }

  tcp {
    port => 5001
    codec => json_lines
    type => "json-app"
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }

  if [fields][service] == "nginx" {
    grok {
      match => { "message" => '%{IPORHOST:client_ip} - %{DATA:user} \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{DATA:request} HTTP/%{NUMBER:http_version}" %{NUMBER:response_code} %{NUMBER:bytes_sent} "%{DATA:referrer}" "%{DATA:user_agent}"' }
    }
    mutate {
      convert => { "response_code" => "integer" "bytes_sent" => "integer" }
    }
  }

  if [fields][service] == "postgres" {
    grok {
      match => { "message" => '%{TIMESTAMP_ISO8601:pg_timestamp} \[%{NUMBER:pid}\] %{DATA:user}@%{DATA:database} %{LOGLEVEL:log_level}:  %{GREEDYDATA:pg_message}' }
    }
  }

  mutate {
    add_field => {
      "environment" => "local"
      "datacenter" => "wsl2-local"
    }
  }

  if [log_level] =~ /ERROR|CRIT|FATAL/ {
    mutate { add_tag => ["error"] }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "devops-logs-%{[fields][service]}-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
  }

  if "error" in [tags] {
    file {
      path => "/var/log/logstash/errors-%{+YYYY-MM-dd}.log"
      codec => json_lines
    }
  }
}
